eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/marketup-realm
        registration:
          api-gateway-client:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: CI0mP2m9SyCv5AsHLqfvShiz6EPX54uR
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marketup-realm
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

server:
  port: 9000