spring:
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      username: root
      password: password
      authentication-database: admin
  web:
    error:
      include-message: always
      include-stacktrace: never

app:
  maintenance:
    message: "Operating System - Version 1.0"

management:
  endpoints:
    web:
      exposure:
        include: "refresh, health"

server:
  port: 8080